baseURL: 'https://rugu.dev/'
languageCode: 'en-us'
title: 'Uğur Erdem Seyfi'

params:
  authorImage: "/ugur_img.jpg"
  connect:
    - linkedin: 'https://www.linkedin.com/in/ugur-erdem-seyfi'
    - github: 'https://github.com/kugurerdem'
    - twitter: 'https://twitter.com/kugurerdem'
    - hackernews: 'https://news.ycombinator.com/user?id=kugurerdem'
    - rss: '/en/index.xml'
  email: "ugur@rugu.dev"
  repo: "https://github.com/kugurerdem/rugudev"

defaultContentLanguageInSubdir: true
languages:
  en:
    contentDir: content/english
    languageName: English
    weight: 0
    params:
      description: "a software developer with a hacker's attitude, interested in philosophy and psychology"
      aboutPath: 'data/en/about.md'
  tr:
    contentDir: content/turkce
    languageName: Turkce
    weight: 1
    params:
      description: "hacker kafalı yazılımcı, felsefe ve psikoloji ile ilgileniyor"
      aboutPath: 'data/en/about.md'
